### ISSUE TITLE
Can we use any continuous integration system? 

### ISSUE THREAD

**Issue by Eullin** [Eullin/Weegot#12]
It may not be necessary but would be nice to try it. What do you think @hexjelly ?

**Comment by hexjelly** [comment]
We should for sure! I made issue for it already #10 😄

**Comment by Eullin** [comment]
Great!!! :D

**Comment by hexjelly** [comment]
Do you think Github Actions is good, or would you like to try something else, Travis, CircleCI, etc.? I guess we can close this issue in favor of #10 which is more specific unless want to use something else.
